!include common.yaml
---
- package: Config::INI::Reader Perl module 
  name: Config-INI
  version: "0.025"
  vendor_source: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Config-INI-0.025.tar.gz
  description: >
    Config::INI::Reader perl module. simple .ini-file format
  rpm: !include rpm.extras.yaml
