!include common.yaml
---
- package: Config::INI::Reader::Ordered Perl module 
  name: Config-INI-Reader-Ordered
  version: "0.020"
  vendor_source: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/{{name}}-{{version}}.{{extension}}
  description: >
    Config::INI::Reader::Ordered perl module. .ini-file parser that returns sections in order
