!include common.yaml
---
- package: Config::INI::Reader::Ordered Perl module 
  name: Config-INI-Reader-Ordered
  version: "{{versions.Config_INI_Reader_Ordered}}"
  loc: "{{versions.Config_INI_Reader_Ordered_loc}}"
  vendor_source: https://cpan.metacpan.org/authors/id/{{loc}}/{{name}}-{{version}}.{{extension}}
  description: >
    Config::INI::Reader::Ordered perl module. .ini-file parser that returns sections in order
