!include common.yaml
---
- package: Config::INI::Reader Perl module 
  name: Config-INI
  version: "{{versions.Config_INI}}"
  loc: "{{versions.Config_INI_loc}}"
  vendor_source: https://cpan.metacpan.org/authors/id/{{loc}}/{{name}}-{{version}}.{{extension}}
  description: >
    Config::INI::Reader perl module. simple .ini-file format
