!include common.yaml
---
- package: ExtUtils::Config Perl module 
  name: ExtUtils-Config
  version: "{{versions.ExtUtils_Config}}"
  loc: "{{versions.ExtUtils_Config_loc}}"
  vendor_source: https://cpan.metacpan.org/authors/id/{{loc}}/{{name}}-{{version}}.{{extension}}
  description: >
    ExtUtils::Config perl module. A wrapper for perl's configuration
