!include common.yaml
---
- package: ExtUtils::Config Perl module 
  name: ExtUtils-Config
  version: "0.008"
  vendor_source: https://cpan.metacpan.org/authors/id/L/LE/LEONT/{{name}}-{{version}}.{{extension}}
  description: >
    ExtUtils::Config perl module. A wrapper for perl's configuration
