!include common.yaml
---
- package: ExtUtils::PkgConfig Perl module 
  name: ExtUtils-PkgConfig
  version: "1.16"
  vendor_source: https://cpan.metacpan.org/authors/id/X/XA/XAOC/{{name}}-{{version}}.{{extension}}
  description: >
    ExtUtils::PkgConfig perl module. simplistic interface to pkg-config
  rpm: !include rpm.extras.yaml
