!include common.yaml
---
- package: ExtUtils::PkgConfig Perl module 
  name: ExtUtils-PkgConfig
  version: "{{versions.ExtUtils_PkgConfig}}"
  loc: "{{versions.ExtUtils_PkgConfig_loc}}"
  vendor_source: https://cpan.metacpan.org/authors/id/{{loc}}/{{name}}-{{version}}.{{extension}}
  description: >
    ExtUtils::PkgConfig perl module. simplistic interface to pkg-config
